# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mix_master', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='song',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
